Models/ErrorViewModel.cs
namespace la_mia_pizzeria_static.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/MoreThanFiveValidationAttribute.cs
using System.ComponentModel.DataAnnotations;
using System.Reflection.Metadata.Ecma335;

namespace la_mia_pizzeria_static.Models
{
    public class MoreThanFiveValidationAttribute : ValidationAttribute 
    {
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            if(value == null)
            {
                string data = (string)value;


                if (data.Split(' ').Count() < 5)
                {
                    return new ValidationResult("La descrizione deve essere di almeno 5 parole");
                }
            }
            

            return ValidationResult.Success;
        }

    }
}

Models/Pizza.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace la_mia_pizzeria_static.Models
{

    [Table("Pizze")]
    public class Pizza
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(25, ErrorMessage = "IL nome inserito è troppo lungo!")]
        public string Name { get; set; }

        [Required(ErrorMessage = "La descrizione è obbligatoria!")]
        [StringLength(25, ErrorMessage = "La descrizione è troppo lunga!")]
        [MoreThanFiveValidation]
        public string Description { get; set; }

        [Required]
        public string Picture { get; set; }

        [Required]
        [Range(1, 25, ErrorMessage = "Inserisci un prezzo valido (tra 1 e 25 euro)")]
        public string Price { get; set; }


        public Pizza()
        {

        }
        public Pizza(string name, string description, string picture, string price)
        {
            int id = 0;
            this.Id = id;
            this.Name = name;
            this.Description = description;
            this.Picture = picture;
            this.Price = price;
            id++;
        }
    }
}

Models/PizzeriaContext.cs
using la_mia_pizzeria_static.Models;
using Microsoft.EntityFrameworkCore;

namespace la_mia_pizzeria_static.Models
{
    public class PizzeriaContext : DbContext
    {
        public DbSet<Pizza> Pizze { get; set; } 
        
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Data Source=localhost;Initial Catalog=la-mia-pizzeria-db;Integrated Security=True");
        }
    }
}

Controllers/EserciziController.cs
using Microsoft.AspNetCore.Mvc;

namespace la_mia_pizzeria_static.Controllers
{
    public class EserciziController : Controller
    {
        public IActionResult Es1()
        {
            return View();
        }

        public IActionResult Es2()
        {
            return View();
        }
        public IActionResult Es3()
        {
            return View();
        }
        public IActionResult Es4()
        {
            return View();
        }
        public IActionResult Es5()
        {
            return View();
        }
        public IActionResult Es6()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace la_mia_pizzeria_static.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PizzaController.cs
using Microsoft.AspNetCore.Mvc;
using la_mia_pizzeria_static.Models;
using System.Collections.Generic;
using Microsoft.IdentityModel.Tokens;

namespace la_mia_pizzeria_static.Controllers
{
    public class PizzaController : Controller
    {
        
        public IActionResult Index()
        {
            List<Pizza> pizze;
            using (PizzeriaContext db = new PizzeriaContext())
            {
                pizze = db.Pizze.OrderBy(pizza => pizza.Name).ToList();
                if(pizze.Count == 0)
                {
                    List<Pizza> pizzas = new List<Pizza> {
                        new Pizza("Margherita", "Pizza con pomodoro, mozzarella e basilico", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Pizza_Margherita_stu_spivack.jpg/1280px-Pizza_Margherita_stu_spivack.jpg", "5"),
                        new Pizza("Marinara", "Pizza con pomodoro, mozzarella e basilico", "https://www.buttalapasta.it/wp-content/uploads/2021/03/pizza-marinara.jpg","4"),
                        new Pizza("Napoli", "Pizza napoletana", "https://wips.plug.it/cips/buonissimo.org/cms/2012/07/pizza-napoli-5.jpg", "6,50"),
                        new Pizza("Wurstel", "pizza con pomodoro mozzarella e wurtel", "https://www.lospicchiodaglio.it/img/ricette/pizzawurstel.jpg", "6"),
                        new Pizza("Salamino piccante",  "Pizza con pomodoro, mozzarella e salamino piccante", "https://api.molinocasillo.com/wp-content/uploads/2020/07/pizza.jpg", "6"),
                        new Pizza("Maialona", "Pizza margherita con wurstel, salsiccia, salamino picccante", "https://media-cdn.tripadvisor.com/media/photo-s/13/a4/63/f8/pizza-maialona.jpg", "7")
                    };

                    foreach (Pizza pizza in pizzas)
                    {
                        db.Add(pizza);
                    }
                    db.SaveChanges();
                    pizze = db.Pizze.OrderBy(pizza => pizza.Name).ToList();
                }
            }
            
            return View(pizze);
        }

        public IActionResult Details(int id)
        {
            Pizza pizza;
            using (PizzeriaContext db = new PizzeriaContext())
            {
                pizza = db.Pizze.Where(pizze => pizze.Id == id).First();
            }
                

            return View(pizza);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View("Create");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Store(Pizza pizza)
        {
            if (!ModelState.IsValid)
            {
                return View("Create", pizza);
            }

            using (PizzeriaContext db = new PizzeriaContext())
            {
                db.Add(new Pizza(pizza.Name, pizza.Description, pizza.Picture, pizza.Price));
                db.SaveChanges();
            }
            
            return RedirectToAction("Index");
        }
    }
}

Views/Esercizi/Es1.cshtml
@{
    // Dichiara una variabile valorizzandola con il tuo nome e una con il tuo cognome. 
    // Stampare in nostro nome e cognome all'interno di un tag h2
    string name = "Agostino";
    string surname = "Piqué";
}

<div class="text-center">
    <h2>@name @surname</h2>
</div>

Views/Esercizi/Es2.cshtml
@{
    // Creare una funzione che stampa la somma dei numeri che vanno da 1 a n (con n passato come parametro - n incluso)
    // Stampare dentro uno span i risultati

    int AddNumbers(int n){
        int a = 0;
        for (var i = 1; i <= n; i++)
        {
            a += i;

        }
        return a;
    };
}

<div class="text-center">
    <span>@AddNumbers(3)</span>
</div>

Views/Esercizi/Es3.cshtml
@{
    // Contare quante volte viene ripetuto il carattere A nella stringa "nel mezzo del cammin di nostra vita",
    // Stampa il risultato in pagina

    int CountLetters(){
        string value = "nel mezzo del cammin di nostra vita";

        char ch = 'e';

        int freq = value.Count(f => (f == ch));

        return freq;

    };
   
}

<div class="text-center">
    <span>@CountLetters()</span>
</div>

Views/Esercizi/Es4.cshtml
@{
    // Creare una List<int> di 20 numeri interi (generati random da 1 a  90 inclusi), 
    // Mostrare in pagina solo i numeri compresi tra 20 e 70

    List<int> numbers = new List<int>();

    List<int> checkedNumbers = new List<int>();

    void CheckNumbers(){

        while(numbers.Count() < 20){
            Random rnd = new Random();
            int randomNumber = rnd.Next(1, 90);
            numbers.Add(randomNumber);
        }

        foreach (int number in numbers)
        {
            if(number > 20 && number < 70){
                checkedNumbers.Add(number);
            }
        }
    };

    CheckNumbers();

}

<div class="text-center">

    @foreach (int n in checkedNumbers)
    {
        <span>@n</span>
    }
</div>

Views/Esercizi/Es5.cshtml
@{
    // Stampare in pagina la data e l'ora attuale (usando la classe DateTime) con 
    // il formato anno-mese-giorno ore:minuti:secondi

    string TodaysDate(){
        string today = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
      
        return today;
    }
}

<div class="text-center">

    <span>@TodaysDate()</span>

</div>

Views/Esercizi/Es6.cshtml
@{
    // Partendo dalla data di oggi (usando la classe DateTime) stampare in pagina:
    // a. la data di 7 giorni fa
    // b. che giorno della settimana è oggi (il risultato dovrà essere il nome del giorno lun, mar, mer)
    // c. che giorno della settimana sarà nello stesso giorno e mese di oggi ma tra un anno 
    // (il risultato dovrà essere il nome del giorno lun, mar, mer)

    DateTime today = DateTime.Now;

    DateTime lastWeek = DateTime.Now.AddDays(-7);

    string todaysDay = today.ToString("dddd");

    string lastWeekDay = lastWeek.ToString("dddd");

    DateTime nextYear = DateTime.Now.AddDays(365);

    string nextYearDay = nextYear.ToString("dddd");

}

<div class="text-center">

    <p>La data della settimana scorsa è: @lastWeek</p>
    <p>Oggi è: @todaysDay</p>
    <p>Il giorno dell'anno prossimo è: @nextYearDay</p>

</div>

Views/Home/Index.cshtml
@{
    //Layout = null;
    Layout = "_layout";
    ViewData["Title"] = "Pizza Home Page";
    string[] pizzas = { "Magherita", "Marinara", "Napoli", "Wurstel", "Salamino piccante", "Maialona" };
    string[] descriptions = { "Pizza con pomodoro, mozzarella e basilico", "Pizza con pomodoro, olio e aglio", "Pizza napoletana", "pizza con pomodoro", "mozzarella e wurtel", "Pizza con pomodoro, mozzarella e salamino piccante", "Pizza margherita con wurstel, salsiccia, salamino picccante" };
    string[] pictures = { "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Pizza_Margherita_stu_spivack.jpg/1280px-Pizza_Margherita_stu_spivack.jpg", "https://www.buttalapasta.it/wp-content/uploads/2021/03/pizza-marinara.jpg", "https://wips.plug.it/cips/buonissimo.org/cms/2012/07/pizza-napoli-5.jpg", "https://www.lospicchiodaglio.it/img/ricette/pizzawurstel.jpg", "https://api.molinocasillo.com/wp-content/uploads/2020/07/pizza.jpg", "https://media-cdn.tripadvisor.com/media/photo-s/13/a4/63/f8/pizza-maialona.jpg"};
    string[] prices = { "5", "4", "6,50", "6", "6", "7" };
}

<div class="text-center">
    <h1>Oh what a splendid pie, pizza pizza pie!!!</h1>
    <h2>Splendid STATIC pies!</h2>

   <table>
        <tr>
            <th>Pizza name</th>
            <th>Description</th>
            <th>Pictures</th>
            <th>Prices</th>
        </tr>
       
        @for (var i = 0; i < pizzas.Length; i++)
        {
            <tr>
                <td>@pizzas[i]</td>
                <td>@descriptions[i]</td>
                <td>
                    <img style="width: 150px; height: 100px;" src="@Url.Content(pictures[i])" alt="pizza-image">
                </td>
                <td>@prices[i]</td>
            </tr>
        }
    </table>
</div>
 

Views/Pizza/Create.cshtml
@model Pizza

<form asp-controller="Pizza" asp-action="Store" method="post">
    @Html.AntiForgeryToken()
    <div class="mb-3">
        <label for="name" class="form-label">Nome Pizza</label>
        <input class="form-control" id="name" asp-for="Name">
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="mb-3">
        <label for="description" class="form-label">Description</label>
        <input class="form-control" id="description" asp-for="Description">
        <span class="text-danger" asp-validation-for="Description"></span>
    </div>
    <div class="mb-3">
        <label for="picture" class="form-label">Picture</label>
        <input class="form-control" id="picture" asp-for="Picture">
        <span class="text-danger" asp-validation-for="Picture"></span>
    </div>
    <div class="mb-3">
        <label for="price" class="form-label">Price</label>
        <input class="form-control" id="price" asp-for="Price">
        <span class="text-danger" asp-validation-for="Price"></span>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

Views/Pizza/Details.cshtml
@model Pizza

<h1>Dettagli della pizza</h1>

<div class="m-auto">
    <div class="card w-50">
        <img src="@Url.Content(Model.Picture)" class="card-img-top" alt="@Model.Name">
        <div class="card-body">
            <h5 class="card-title">@Model.Name</h5>
            <p class="card-text">@Model.Description</p>
            <p>&euro; @Model.Price</p>
            <a href="@Url.Action("Index", "Pizza")" class="btn btn-primary">Torna alla schermata principale</a>
        </div>
    </div>
</div>

Views/Pizza/Index.cshtml
@{
    Layout = "_Layout";
}

@model List<Pizza> 

<h1>Ciao pizzeria!</h1>

<h3>Ecco le nostre pizze: </h3>

<table class="table">
    <thead>
        <tr>
            <th scope="col">#Id</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Jucie image</th>
            <th scope="col">Price</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @{
            int count = 0;
        }
        @foreach (Pizza pizza in Model)
        {
            <tr>
                <th scope="row">@count</th>
                <td>@pizza.Name</td>
                <td>@pizza.Description</td>
                <td><img style="width: 150px; height: 100px;" src="@Url.Content(@pizza.Picture)" alt="@pizza.Name"></td>
                <td>&euro; @pizza.Price</td>
                <td><a href="@Url.Action("Details", "Pizza", new {id = pizza.Id})" >Dettagli</a></td>
            </tr>
            count++;
        }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - la_mia_pizzeria_static</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">la_mia_pizzeria_static</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pizza" asp-action="Index">Pizze</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pizza" asp-action="Create">Crea Pizza</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Esercizi" asp-action="Es1">Esercizio 1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Esercizi" asp-action="Es2">Esercizio 2</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Esercizi" asp-action="Es3">Esercizio 3</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Esercizi" asp-action="Es4">Esercizio 4</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Esercizi" asp-action="Es5">Esercizio 5</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Esercizi" asp-action="Es6">Esercizio 6</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - la_mia_pizzeria_static - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>